name: Macro Data Pipeline

on:
  schedule:
    # Every 3 days at 17:00 UTC
    - cron: "0 17 */3 * *"
  workflow_dispatch: {}

jobs:

  macro_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run macro indicators script
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python backend/indicators_pipeline/macro_data.py